### ISSUE TITLE
Step Allure Report failed

### ISSUE THREAD

**Issue by simonwilbert** [allure-framework/allure-teamcity#49]
[allure-results.zip](https://github.com/allure-framework/allure-teamcity/files/824333/allure-results.zip)
Hi,

Have just installed latest allure report and it fails to generate the report which looks like its due to a parsing error?

[12:01:28]Step 3/3: Allure Report (6s)
[12:01:30][Step 3/3] Starting: C:\BuildAgent\jre\bin\java.exe -Dallure.config=D:\BuildAgent\temp\buildTmp\allure-config1538927833471753088\allure.properties -Dallure.home=C:\BuildAgent\tools\allure-commandline -classpath C:\BuildAgent\tools\allure-commandline\lib/*;C:\BuildAgent\tools\allure-commandline\conf ru.yandex.qatools.allure.CommandLine -v generate D:\BuildAgent\work\40ce24ae9259cf8\allure-results --output D:\BuildAgent\temp\buildTmp\allure-report2133115941729705135\allure-report
[12:01:30][Step 3/3] in directory: D:\BuildAgent\work\40ce24ae9259cf8
[12:01:33][Step 3/3] [main] DEBUG ru.yandex.qatools.allure.data.utils.ServiceLoaderUtils - Found Plugin [ru.yandex.qatools.allure.data.plugins.MigrationPlugin@e24091]
[12:01:33][Step 3/3] [main] DEBUG ru.yandex.qatools.allure.data.utils.ServiceLoaderUtils - Found Plugin [ru.yandex.qatools.allure.data.plugins.XUnitPlugin@86b9e3]
[12:01:33][Step 3/3] [main] DEBUG ru.yandex.qatools.allure.data.utils.ServiceLoaderUtils - Found Plugin [ru.yandex.qatools.allure.data.plugins.TimelinePlugin@1dac5ef]
[12:01:33][Step 3/3] [main] DEBUG ru.yandex.qatools.allure.data.utils.ServiceLoaderUtils - Found Plugin [ru.yandex.qatools.allure.data.plugins.BehaviorsPlugin@509ffa]
[12:01:33][Step 3/3] [main] DEBUG ru.yandex.qatools.allure.data.utils.ServiceLoaderUtils - Found Plugin [ru.yandex.qatools.allure.data.plugins.DefectsPlugin@567e20]
[12:01:33][Step 3/3] [main] DEBUG ru.yandex.qatools.allure.data.utils.ServiceLoaderUtils - Found Plugin [ru.yandex.qatools.allure.data.plugins.GraphPlugin@1d07cbb]
[12:01:33][Step 3/3] [main] DEBUG ru.yandex.qatools.allure.data.utils.ServiceLoaderUtils - Found Plugin [ru.yandex.qatools.allure.data.plugins.EnvironmentPlugin@3570b7]
[12:01:33][Step 3/3] [main] DEBUG ru.yandex.qatools.allure.data.utils.ServiceLoaderUtils - Found Plugin [ru.yandex.qatools.allure.data.plugins.TotalPlugin@947bc5]
[12:01:34][Step 3/3] Exception in thread "main" java.lang.NumberFormatException: For input string: ""
[12:01:34][Step 3/3] 	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[12:01:34][Step 3/3] 	at java.lang.Long.parseLong(Long.java:601)
[12:01:34][Step 3/3] 	at java.lang.Long.valueOf(Long.java:803)
[12:01:34][Step 3/3] 	at com.sun.xml.internal.bind.DatatypeConverterImpl._parseLong(DatatypeConverterImpl.java:118)
[12:01:34][Step 3/3] 	at ru.yandex.qatools.allure.model.TestCaseResult_JaxbXducedAccessor_stop.parse(TransducedAccessor_field_Long.java:50)
[12:01:34][Step 3/3] 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.StructureLoader.startElement(StructureLoader.java:195)
[12:01:34][Step 3/3] 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:559)
[12:01:34][Step 3/3] 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:538)
[12:01:34][Step 3/3] 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:153)
[12:01:34][Step 3/3] 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
[12:01:34][Step 3/3] 	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:380)
[12:01:34][Step 3/3] 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2787)
[12:01:34][Step 3/3] 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
[12:01:34][Step 3/3] 	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
[12:01:34][Step 3/3] 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
[12:01:34][Step 3/3] 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
[12:01:34][Step 3/3] 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
[12:01:34][Step 3/3] 	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
[12:01:34][Step 3/3] 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
[12:01:34][Step 3/3] 	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
[12:01:34][Step 3/3] 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:243)
[12:01:34][Step 3/3] 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:221)
[12:01:34][Step 3/3] 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:276)
[12:01:34][Step 3/3] 	at javax.xml.bind.JAXB.unmarshal(JAXB.java:242)
[12:01:34][Step 3/3] 	at ru.yandex.qatools.allure.commons.AllureFileUtils.unmarshal(AllureFileUtils.java:59)
[12:01:34][Step 3/3] 	at ru.yandex.qatools.allure.commons.AllureFileUtils.unmarshal(AllureFileUtils.java:50)
[12:01:34][Step 3/3] 	at ru.yandex.qatools.allure.commons.AllureFileUtils.unmarshal(AllureFileUtils.java:40)
[12:01:34][Step 3/3] 	at ru.yandex.qatools.allure.data.io.TestSuiteReader$TestSuiteResultIterator.next(TestSuiteReader.java:48)
[12:01:34][Step 3/3] 	at ru.yandex.qatools.allure.data.io.TestSuiteReader$TestSuiteResultIterator.next(TestSuiteReader.java:1)
[12:01:34][Step 3/3] 	at ru.yandex.qatools.allure.data.io.TestCaseReader$TestCaseResultIterator.nextSuite(TestCaseReader.java:46)
[12:01:34][Step 3/3] 	at ru.yandex.qatools.allure.data.io.TestCaseReader$TestCaseResultIterator.hasNext(TestCaseReader.java:56)
[12:01:34][Step 3/3] 	at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:57)
[12:01:34][Step 3/3] 	at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:53)
[12:01:34][Step 3/3] 	at ru.yandex.qatools.allure.AllureMain.main(AllureMain.java:48)
[12:01:34][Step 3/3] Command aborted due to exception {}.
[12:01:34][Step 3/3] org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
[12:01:34][Step 3/3] 	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
[12:01:34][Step 3/3] 	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
[12:01:34][Step 3/3] 	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
[12:01:34][Step 3/3] 	at ru.yandex.qatools.allure.command.ReportGenerate.runUnsafe(ReportGenerate.java:48)
[12:01:34][Step 3/3] 	at ru.yandex.qatools.allure.command.AbstractCommand.run(AbstractCommand.java:52)
[12:01:34][Step 3/3] 	at ru.yandex.qatools.allure.CommandLine.main(CommandLine.java:46)
[12:01:34][Step 3/3] Delete <D:\BuildAgent\temp\buildTmp\allure-commandline1008710331291154652\exec5699053940107549519\generate.jar>
[12:01:34][Step 3/3] Delete <D:\BuildAgent\temp\buildTmp\allure-commandline1008710331291154652\exec5699053940107549519>
[12:01:34][Step 3/3] Delete <D:\BuildAgent\temp\buildTmp\allure-commandline1008710331291154652>
[12:01:34][Step 3/3] Process exited with code 1
[12:01:35][Step 3/3] Step Allure Report failed

**Comment by eroshenkoam** [comment]
fixed at 2.5
