### ISSUE TITLE
Teamcity. Error. Unable to delete directory.

### ISSUE THREAD

**Issue by RMike88** [allure-framework/allure-teamcity#83]
I have a problem. I use allure with teamcity. I have two servers teamcity.  I get a mistake in build step teamcity. In the directory allure on the teamcity agent I can not delete folder history and I don't access this folder. 

Version Teamcity: 2018.2.1 (build 61078)
Version java: 8 64 bit.
Teamcity agent-based operating system windows 
   OS Name:                   Microsoft Windows Server 2016 Standard
   OS Version:                10.0.14393 N/A Build 14393 
Teamcity server-based operating system linux

Besides this I have a second server teamcity. This is old version server. 
His version is 10.0.5 (build 42677).  
Version java:  8 32 bit.  
Teamcity agent-based operating system windows
  OS Name:                 Microsoft Windows Server 2012 R2 Standard
  OS Version:                6.3.9600 N/A build 9600
Teamcity server-based operating system windows
It has the same mistake.

There's a 'history' dir in C:\BuildAgent\work\5ed8e22513d0043d\allure and it's in RO mode even for an admin user. Basically, I can't even open it as admin user.

Log teamcity:

 java.io.IOException: Unable to delete directory C:\BuildAgent\work\5ed8e22513d0043d\allure.
 java.io.IOException: Unable to delete directory C:\BuildAgent\work\5ed8e22513d0043d\allure.
at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:873)
at io.qameta.allure.teamcity.AllureBuildServiceAdapter.clearReport(AllureBuildServiceAdapter.java:193)
at io.qameta.allure.teamcity.AllureBuildServiceAdapter.beforeProcessStarted(AllureBuildServiceAdapter.java:108)
at jetbrains.buildServer.agent.runner2.SingleCommandLineBuildSessionAdapter.beforeProcessStarted(SingleCommandLineBuildSessionAdapter.java:58)
at jetbrains.buildServer.agent.runner2.GenericCommandLineBuildProcess.executeProcess(GenericCommandLineBuildProcess.java:62)
at jetbrains.buildServer.agent.runner2.GenericCommandLineBuildProcess.waitFor(GenericCommandLineBuildProcess.java:269)
	at jetbrains.buildServer.agent.impl.buildStages.runnerStages.start.CallRunnerStage.doBuildStage(CallRunnerStage.java:62)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:25)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:18)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor.doStages(RunnerStagesExecutor.java:18)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunnerContextExecutor.callRunnerStages(RunnerContextExecutor.java:43)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.StepExecutor.processNextStep(StepExecutor.java:25)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeRunnerStep(ForEachBuildRunnerStage.java:138)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.runStep(ForEachBuildRunnerStage.java:123)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeBuildRunners(ForEachBuildRunnerStage.java:83)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.doBuildStage(ForEachBuildRunnerStage.java:44)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:31)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor.doStages(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.BuildRunActionImpl.doStages(BuildRunActionImpl.java:75)
	at jetbrains.buildServer.agent.impl.BuildRunActionImpl.runBuild(BuildRunActionImpl.java:55)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.doActualBuild(BuildAgentImpl.java:300)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.access$100(BuildAgentImpl.java:54)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl$1.run(BuildAgentImpl.java:264)
	at java.lang.Thread.run(Thread.java:745)
[Step 4/4] java.io.IOException: Unable to delete directory C:\BuildAgent\work\5ed8e22513d0043d\allure.
[Step 4/4] Step Allure Report failed with unexpected error

**Comment by konstest** [comment]
Hi!
@RMike88 I have the same problem, how do you resolved her ?
TeamCity server 2018.2 (build 60925)
Allure Plugin version:  2.9.0

**Comment by konstest** [comment]
[problem solution](https://github.com/allure-framework/allure-teamcity/issues/80#issuecomment-506666355)
